### ISSUE TITLE
Implement release and versioning strategy for the relayer

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#18]
There needs to be a release and versioning strategy for this repository. I propose to keep it in line with`cosmos-sdk` versioning with an option for `dev` releases. This should be able to be easily accomplished with github actions. Releases should contain built binaries for `macos` and `linux` and should be able to be triggered by `v*` tag pushes. The built binaries should also be able to report their version through `relayer version`

**Comment by zmanian** [comment]
If we are going to release binaries, I think we should probably have some kind of reproducible build strategy

**Comment by jackzampolin** [comment]
Ok, the build process is currently producing binaries (see https://github.com/cosmos/relayer/actions/runs/40806410). We could just port over the `gaia` build stuff to here and hook it up in actions.

**Comment by jackzampolin** [comment]
versioning implemented: https://github.com/cosmos/relayer/pull/67

Will implement releases via tag push as github actions.

**Comment by jackzampolin** [comment]
Ok, I've also added actions for creating releases on tag pushes. Going to go ahead and close this issue.
