### ISSUE TITLE
Implement IBC Queries

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#19]
The following queries for IBC need to be implemented on the relayer. All of these queries should also return proofs. They will be mainly useful for use in `tx` commands (as a way to query the chain for the necessary on-chain data) but should also be exposed to the user:

  * [x] `header [chain-id] [height]` - Query the header at a given height
  * [x] `node-state [chain-id] [height]` - Query the node state at a given height or latest if height not passed
  * [x] `client [chain-id] [client-id]` - Query details for an individual client
  * [x] `clients [chain-id]` - Query the list of clients on a given chain
  * [x] `connection [chain-id] [connection-id]` - Query details for an individual connection
  * [x] `connections [chain-id] [client-id]`- Query the list of connections associated with a client
  * [x] `channel [chain-id] [connection-id] [channel-id]` - Query details for an individual channel
  * [x] `channels [chain-id] [connection-id]` - Query the list of channels associated with a client
  * [x] `seq-send [chain-id] [channel-id]` - Query the `seq-send` for the configured key on a given chain and channel
  * [x] `seq-recv [chain-id] [channel-id]` - Query the `seq-recv` for the configured key on a given chain and channel
  * [ ] `packet-commitment`
  * [ ] `packet-ack`
  * [ ] `packet-timeout`
  * [ ] `packet-data` - NOTE: This should be implemented by querying a full node with specific indices setup

**Comment by cwgoes** [comment]
As these queries require proofs, they must all be direct store queries and can be performed using the existing store query logic, so no additional modifications are needed on the SDK side, correct?

**Comment by jackzampolin** [comment]
@cwgoes thats the plan, and the way it is currently implemented. All queries from the relayer return proofs. See `QueryConnection` https://github.com/cosmos/relayer/blob/master/relayer/query.go#L153

**Comment by jackzampolin** [comment]
Currently we are debugging the proofs not returning properly

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/iqlusioninc/relayer/issues/30
