### ISSUE TITLE
Implement Relayer Strategies and Start command

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#21]
The relayer start command is currently worse than a stub. The basic design is there, but there are many implementation details to be worked out. Also once the transactions and queries for the relayer are created, they can easily be composed into strategies. Some potential strategies:

- [ ] naive - Relay everything from all configured to all configured chains
- [ ] two-chains - relay only between two chains
- [ ] specific clients/connections/channels 
- [ ] others....

**Comment by cwgoes** [comment]
Another useful option: relay only transactions sent from or to specific addresses (e.g. the user's addr).

**Comment by jackzampolin** [comment]
These are features we can add to the `Path` object later IMO and not necessary for the MVP. I think getting the structure right to accommodate those things and then adding features like this later is the right way to go.

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/cosmos/relayer/issues/48.
