### ISSUE TITLE
Issue with create-client

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#26]
When creating another client for the same chain with a different ID there is an error. To reproduce:

```
$ relayer tx clients ibc0 ibc1 ibconeclient ibczeroclient
$ relayer tx clients ibc0 ibc1 otheridentone otheridentzero
{"height":"1534","txhash":"AAA41FDDB1657D0633BD93725DA8970D7EEA8C8A73DEDFF6EA8E7E310C6DD25C","codespace":"client","code":1,"raw_log":"internal error","gas_wanted":"200000","gas_used":"45751"}
{"height":"1535","txhash":"93F4DCD683CCFA9AD9AB602C09B1A558A0B05FCCF7482B9761C8E9240BB111F7","codespace":"client","code":1,"raw_log":"internal error","gas_wanted":"200000","gas_used":"45751"}
```

**Comment by cwgoes** [comment]
"internal_error", that's not very helpful, I'll take a look.

Why are there two transactions? Are we attempting to create two clients (one per chain)?

**Comment by jackzampolin** [comment]
@cwgoes exactly, and no that internal error isn't helpful at all

**Comment by cwgoes** [comment]
Seems like "internal error" is from [types/errors/abci.go](https://github.com/cosmos/cosmos-sdk/blob/ibc-alpha/types/errors/abci.go#L161) (unsure why it is referring to "Weave", maybe this code was borrowed from that SDK?) - somewhere we must be throwing an error with code "1".

**Comment by cwgoes** [comment]
Ah it turns out the problem is actually something about which identifier is used - 

```bash
relayer tx clients ibc0 ibc1 ibconeclient ibczeroclient
relayer tx clients ibc0 ibc1 ibconeclienta ibczeroclienta
relayer tx clients ibc0 ibc1 ibconeclientb ibczeroclientb
```

works just fine. Maybe numbers aren't valid in identifiers?

It should definitely return a different error though.

**Comment by cwgoes** [comment]
Yeah, numbers aren't valid in identifiers - [x/ibc/24-host/validate.go](https://github.com/cosmos/cosmos-sdk/blob/ibc-alpha/x/ibc/24-host/validate.go#L25):

```golang
func defaultIdentifierValidator(id string, min, max int) error {
	// valid id MUST NOT contain "/" separator
	if strings.Contains(id, "/") {
		return sdkerrors.Wrapf(ErrInvalidID, "identifier %s cannot contain separator '/'", id)
	}
	// valid id must be between 10 and 20 characters
	if len(id) < min || len(id) > max {
		return sdkerrors.Wrapf(ErrInvalidID, "identifier %s has invalid length: %d, must be between %d-%d characters", id, len(id), min, max)
	}
	// valid id must contain only lower alphabetic characters
	if !isAlphaLower(id) {
		return sdkerrors.Wrapf(ErrInvalidID, "identifier %s must contain only lowercase alphabetic characters", id)
	}
	return nil
}

// DefaultClientIdentifierValidator is the default validator function for Client identifiers
// A valid Identifier must be between 10-20 characters and only contain lowercase
// alphabetic characters,
func DefaultClientIdentifierValidator(id string) error {
	return defaultIdentifierValidator(id, 10, 20)
}
```

I still don't understand the "internal error" bit though, it should be `ErrInvalidID`.

Also, the `"codespace"` in the returned JSON is `undefined`, that may be related. Perhaps there is some issue in how we're registering errors or translating the codespaces & codes in module-specific namespaced errors?

**Comment by jackzampolin** [comment]
I do know there was a recent refactor of the errors in the SDK cc @marbar3778 @alexanderbez

**Comment by alexanderbez** [comment]
These are txs? Are they failing in the handler or prior to the handler? Are they failing during validate basic?

Not sure why the error refactor is brought up. It would have nothing to do with the issue here. I would first pinpoint where the tx is failing and then we can determine why the appropriate response is not being returned.

**Comment by cwgoes** [comment]
The tx is failing when `DefaultClientIdentifierValidator` is called in `msg.ValidateBasic()`:

https://github.com/cosmos/cosmos-sdk/blob/ibc-alpha/x/ibc/02-client/types/msgs.go#L62

```golang
func (msg MsgCreateClient) ValidateBasic() error {
	if clientType := exported.ClientTypeFromString(msg.ClientType); clientType == 0 {
		return sdkerrors.Wrap(ErrInvalidClientType, msg.ClientType)
	}
	if msg.ConsensusState == nil {
		return ErrInvalidConsensus
	}
	if err := msg.ConsensusState.ValidateBasic(); err != nil {
		return err
	}
	if msg.Signer.Empty() {
		return sdkerrors.ErrInvalidAddress
	}
	return host.DefaultClientIdentifierValidator(msg.ClientID)
}
```

**Comment by alexanderbez** [comment]
I see. Well, that indeed should execute the following block in `BaseApp#CheckTx`:

```go
gInfo, result, err := app.runTx(mode, req.Tx, tx)
if err != nil {
	return sdkerrors.ResponseCheckTx(err, gInfo.GasWanted, gInfo.GasUsed)
}
```

Where `ResponseCheckTx`:

```go
func ResponseCheckTx(err error, gw, gu uint64) abci.ResponseCheckTx {
	space, code, log := ABCIInfo(err, false)
	return abci.ResponseCheckTx{
		Codespace: space,
		Code:      code,
		Log:       log,
		GasWanted: int64(gw),
		GasUsed:   int64(gu),
	}
}
```

Where `ABCIInfo`:

```go
func ABCIInfo(err error, debug bool) (codespace string, code uint32, log string) {
	if errIsNil(err) {
		return "", SuccessABCICode, ""
	}

	encode := defaultErrEncoder
	if debug {
		encode = debugErrEncoder
	}

	return abciCodespace(err), abciCode(err), encode(err)
}
```

Where `encode`:

```go
func Redact(err error) error {
	if ErrPanic.Is(err) {
		return errors.New(internalABCILog)
	}
	if abciCode(err) == internalABCICode {
		return errors.New(internalABCILog)
	}
	return err
}
```

This error refactor was done by Ethan which is ported from Weave and modified by me (slightly). So hence there are remnants of "weave" in the comments (I need to remove those).

Point being, there is the following block:

```go
	if abciCode(err) == internalABCICode {
		return errors.New(internalABCILog)
	}
```

I'm not sure why this is and I didn't know about it. We should have all registered errors start at code `2` and above.

I will update all the modules to do this. Thanks for the catch!

**Comment by jackzampolin** [comment]
I think this has FINALLY been solved in the `jack/debuggin` branch.
