### ISSUE TITLE
Make Chain an interface and cosmos-sdk-chain an implementation

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#35]
We should move the `Chain` struct and all associated code to its own package so that it could be used by other relayer implementations. Ideally we could then move it to the SDK once it has stabilized and us it to refactor `CLIContext` with cleaner abstractions.

**Comment by jackzampolin** [comment]
This actually should be specified as an interface of the methods needed for the relayer and the current chain implementation should be moved into a `chains/tendermint` package as a concrete implemenation.

**Comment by cwgoes** [comment]
@jackzampolin Should this be closed or moved to https://github.com/iqlusioninc/relayer?
