### ISSUE TITLE
Chains Add improvements

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#51]
As a follow-on from https://github.com/cosmos/relayer/pull/49, there are a couple of features I would like to see added to `relayer chains add`. 

- `relayer chains add --url [url]` - This would fetch the json and add the chain after verifying it. Think usage from a github repo (https://raw.githubusercontent.com/cosmos/relayer/tree/master/demo/ibc0.json)
- `relayer chains add --cosmos [url]` - This would query the `/genesis` endpoint to fetch most of the data and then would rely on sane defaults for `gas` and `gasPrices` based on that. This is basically figuring out how to unmarshal gaia based config.

**Comment by cwgoes** [comment]
Closing per https://github.com/iqlusioninc/relayer/issues/35.
