### ISSUE TITLE
Basic web-hook alerting system

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#57]
The relayer should have some options for how to handle transactions that fail for insufficient fees. One idea is to provide an slack, telegram or other outputs for these alerts.

**Comment by zmanian** [comment]
Maybe a webhook with a JSON payload?

**Comment by cwgoes** [comment]
Insufficient balance to pay fees, insufficient gas allocated for computation, or insufficient fees to be confirmed? These are all different failure cases & will need to be handled separately.

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/iqlusioninc/relayer/issues/31.
