### ISSUE TITLE
Update Period is set as Trusting Period

### ISSUE THREAD

**Issue by cmwaters** [cosmos/relayer-archive#7]
updatePeriod is never used

```
var (
	lcMap map[string]*lite.Client // chainID => client

	trustedHash    []byte
	trustedHeight  int64
	trustingPeriod time.Duration
	updatePeriod   time.Duration
	url            string
)
```

Instead the update period for the lite client is set as `lite.UpdatePeriod(c.TrustOptions.Get().Period))` where the trusted period is set here:

```
if trustingPeriod > 0 {
	chain.TrustOptions.Period = trustingPeriod.String()
}
```

**Comment by melekes** [comment]
Update period should be a config option imho.

**Comment by cmwaters** [comment]
" Update period should be a config option imho."
As in an option in the command line or one set in the config file?

**Comment by melekes** [comment]
config file

reset cmd will have a update-period flag, but we don't have to implement that now

**Comment by cmwaters** [comment]
Okay, I will add that in
