### ISSUE TITLE
No ’relayer q balance‘ likely

### ISSUE THREAD

**Issue by jgr-great** [cosmos/relayer-archive#74]
➜  relayer git:(master) ✗ relayer q balance ibc1
query functionality for configured chains

Usage:
  relayer query [command]

Aliases:
  query, q

Available Commands:
  account            Use configured RPC client to fetch the account balance of the relayer account
  channel            Query the client for a counterparty chain
  channels           Query for all channels on a given chain
  client             Query the client for a counterparty chain
  client-connections Query the client for a counterparty chain
  clients            Query the client for a counterparty chain
  connection         Query the client for a counterparty chain
  connections        Query for all connections on a given chain
  header             Use configured RPC client to fetch a header at a given height from a configured chain
  node-state         Query the consensus state of a client at a given height, or at latest height if height is not passed
  packet-ack         Query the commitment for a given packet
  packet-commit      Query the commitment for a given packet
  seq-send           Query the next sequence send for a given channel

Flags:
  -h, --help   help for query

Global Flags:
      --config string   set config file (default "config.yaml")
      --home string     set home directory (default "/Users/jiang/.relayer")

Use "relayer query [command] --help" for more information about a command.
subcommand is required

**Comment by jackzampolin** [comment]
This repo is a mirror please go to https://github.com/iqlusioninc/relayer` for the up to date code.

This feature is added now.
