### ISSUE TITLE
Alternative Providers

### ISSUE THREAD

**Issue by cmwaters** [cosmos/relayer-archive#8]
Lite client only has a primary provider but not the ability to add alternative providers for verifying headers.

**Comment by jackzampolin** [comment]
I think the way to add this feature would be to make the `Config.RPCAddr` property an `[]string`

**Comment by melekes** [comment]
NOTE: the number of alternative full nodes must be greater than 0 (more is better for security reasons). Ideally we'd show the user a warning: "Number of alternative providers is too low" if it's less than 4-5.

**Comment by cwgoes** [comment]
@jackzampolin Should this be closed or moved to https://github.com/iqlusioninc/relayer?

**Comment by jackzampolin** [comment]
Should be closed, I've got the lite client integrated.
