### ISSUE TITLE
err(channels: channel not found)

### ISSUE THREAD

**Issue by cryptophonic** [cosmos/relayer-archive#83]
Following the instructions in the readme, issuing the transfer command gives a "channel not found" error.  Not sure how to debug or proceed.

$ rly tx transfer ibc0 ibc1 10000n0token true $(rly keys show ibc1 testkey -a)
I[2020-03-22|09:40:38.752] ✘ [ibc0]@{613} - msg(transfer) err(channels: channel not found) 
Error: failed to send first transaction

$ rly version
version: 0.1.0-35-g4638dc5
commit: 4638dc5c098732343c2ae13d50d36b01d98278ef
cosmos-sdk: v0.34.4-0.20200318160616-b8295506615b
go: go1.14 linux/amd64

$ gaiad version
0.0.0-239-gfe439e5

**Comment by jackzampolin** [comment]
@mjackson001 thanks for trying this out! the most current relayer code is over at https://github.com/iqlusioninc/relayer and there are updated instructions there. This looks like you need to run `rly tx full-path ibc0 ibc1` before trying the transfer.
