### ISSUE TITLE
Atomic swap support

### ISSUE THREAD

**Issue by Alexader** [cosmos/relayer-archive#94]
When I followed the demo instructions to run a cross chain transfer, I found that the if the command `rly tx transfer ibc0 ibc1 10000n0token true $(rly keys show ibc1 testkey)` failed, the balance in ibc0 will reduce and can't get rollbacked. Is there any atmoic swap guarantee mechanism in ibc now or any support in future plan?

**Comment by cwgoes** [comment]
Hmm, that's odd - can you re-open this on https://github.com/iqlusioninc/relayer with a detailed list of instructions to reproduce and the result of queries after you execute the commands?
